In [87]:
import pandas as pd
import numpy as np

In [88]:
dataset = pd.read_csv('dataset_modified.csv')

In [89]:
dataset.head()

Unnamed: 0                                              title  \
0       23698  House intel panel chief says did not meet Trum...   
1       28188  JUDGE NAPOLITANO: Samsung Allowed British Inte...   
2       41061  ATLANTA: PANDEMONIUM As World’s Largest Airpor...   
3       36180  Brazil prosecutors seek to extend Batista dete...   
4       40515  CHARLES BARKLEY Says Anyone Who Criticizes Oba...   

                                                text       subject  \
0  WASHINGTON (Reuters) - U.S. House Intelligence...  politicsNews   
1  .@Judgenap: Samsung allowed British intelligen...     left-news   
2  There has to something more to this story than...      politics   
3  SAO PAULO (Reuters) - The Office of Brazil s P...     worldnews   
4  On March 20, 2016 Barkley had this to say abou...     left-news   

                  date  label  
0      March 27, 2017     1.0  
1          Mar 9, 2017    0.0  
2         Dec 17, 2017    0.0  
3  September 14, 2017     1.0  
4          Apr 8, 2016    0.0

In [90]:
import tensorflow as tf
from tensorflow.keras.layers import Embedding,LSTM,Dense, Bidirectional, Dropout
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot 

In [91]:
dataset = dataset.dropna()

In [92]:
dataset.head()

Unnamed: 0                                              title  \
0       23698  House intel panel chief says did not meet Trum...   
1       28188  JUDGE NAPOLITANO: Samsung Allowed British Inte...   
2       41061  ATLANTA: PANDEMONIUM As World’s Largest Airpor...   
3       36180  Brazil prosecutors seek to extend Batista dete...   
4       40515  CHARLES BARKLEY Says Anyone Who Criticizes Oba...   

                                                text       subject  \
0  WASHINGTON (Reuters) - U.S. House Intelligence...  politicsNews   
1  .@Judgenap: Samsung allowed British intelligen...     left-news   
2  There has to something more to this story than...      politics   
3  SAO PAULO (Reuters) - The Office of Brazil s P...     worldnews   
4  On March 20, 2016 Barkley had this to say abou...     left-news   

                  date  label  
0      March 27, 2017     1.0  
1          Mar 9, 2017    0.0  
2         Dec 17, 2017    0.0  
3  September 14, 2017     1.0  
4          Apr 8, 2016    0.0

In [93]:
x= dataset.drop('label',axis=1)

In [94]:
x.head()

Unnamed: 0                                              title  \
0       23698  House intel panel chief says did not meet Trum...   
1       28188  JUDGE NAPOLITANO: Samsung Allowed British Inte...   
2       41061  ATLANTA: PANDEMONIUM As World’s Largest Airpor...   
3       36180  Brazil prosecutors seek to extend Batista dete...   
4       40515  CHARLES BARKLEY Says Anyone Who Criticizes Oba...   

                                                text       subject  \
0  WASHINGTON (Reuters) - U.S. House Intelligence...  politicsNews   
1  .@Judgenap: Samsung allowed British intelligen...     left-news   
2  There has to something more to this story than...      politics   
3  SAO PAULO (Reuters) - The Office of Brazil s P...     worldnews   
4  On March 20, 2016 Barkley had this to say abou...     left-news   

                  date  
0      March 27, 2017   
1          Mar 9, 2017  
2         Dec 17, 2017  
3  September 14, 2017   
4          Apr 8, 2016

In [95]:
label = dataset['label']

In [96]:
label.head()

0    1.0
1    0.0
2    0.0
3    1.0
4    0.0
Name: label, dtype: float64

In [97]:
label.value_counts()

0.0    23481
1.0    21417
Name: label, dtype: int64

In [98]:
x.shape

(44898, 5)

In [99]:
label.shape

(44898,)

In [100]:
voc_size=5000

In [101]:
msg=x.copy()
msg['title'][5]

'Barely a quarter of Catalans want to pursue split from Spain: poll'

In [102]:
msg.reset_index(inplace=True)

In [103]:
import nltk
import re
from nltk.corpus import stopwords

In [104]:
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()
corpus=[]
for i in range (0, len(msg)):
    review= re.sub('[^a-zA-z]',' ',msg['title'][i])
    review= review.lower()
    review=review.split()
    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review=' '.join(review)
    corpus.append(review)
print(i)

44897


In [105]:
corpus

['hous intel panel chief say meet trump white hous visit',
 'judg napolitano samsung allow british intellig spi american tv [video]',
 'atlanta pandemonium world largest airport goe dark airport evacu flight cancel [video]',
 'brazil prosecutor seek extend batista detent sourc say',
 'charl barkley say anyon critic obama racist gay right import religi freedom america [video]',
 'bare quarter catalan want pursu split spain poll',
 'syrian armi alli km deir al zor enclav state tv',
 'u announc near million humanitarian aid syria',
 'trump expect name former goldman banker mnuchin treasuri sourc',
 'man yell cnn fake news live nyc broadcast',
 'jess watter like never seen watch rip juan william call trump famili unpatriot school corrupt democrat parti tie commun crook hillari barack obama',
 'russian communist drop veteran select surpris candid challeng putin',
 'cambodian govern file lawsuit dissolv main opposit parti',
 'friend barack son beau got sick bring joe biden brink tear video',

In [106]:
onehot_repr=[one_hot(words,voc_size)for words in corpus] 
onehot_repr

[[3657, 3987, 3895, 3397, 347, 4561, 2059, 925, 3657, 614],
 [4779, 2859, 3141, 3557, 3614, 1937, 3942, 1824, 2732, 1798],
 [4193, 2968, 927, 860, 965, 3379, 40, 965, 558, 4769, 4816, 1798],
 [211, 773, 352, 2855, 3263, 3710, 4135, 347],
 [1905,
  3638,
  347,
  1298,
  1994,
  1281,
  3499,
  1935,
  4950,
  1156,
  1115,
  191,
  2624,
  1798],
 [1268, 3907, 4612, 3823, 3839, 1750, 3585, 228],
 [1904, 3415, 2911, 504, 1556, 3196, 1865, 2868, 4881, 2732],
 [3872, 3297, 2849, 3214, 2790, 307, 1346],
 [2059, 2078, 4784, 3868, 2243, 2604, 853, 1322, 4135],
 [3378, 756, 4212, 2377, 313, 4912, 2474, 4400],
 [1080,
  1573,
  3126,
  2193,
  1650,
  465,
  765,
  3925,
  3399,
  2457,
  2059,
  144,
  3481,
  258,
  991,
  3457,
  3326,
  3557,
  512,
  2923,
  4085,
  1577,
  1281],
 [3487, 1243, 4268, 1494, 3251, 415, 4247, 2450, 3598],
 [2371, 1923, 2560, 2475, 685, 2219, 1014, 3326],
 [3649, 1577, 293, 4752, 1518, 1917, 473, 4882, 665, 4594, 4542, 1798],
 [3199, 2375, 2238, 4085, 4162, 4

In [107]:
sent_length=20
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0 ...  925 3657  614]
 [   0    0    0 ... 1824 2732 1798]
 [   0    0    0 ... 4769 4816 1798]
 ...
 [   0    0    0 ... 4005 1100 1845]
 [   0    0    0 ...  322 4775 1798]
 [   0    0    0 ...  865 3803 3350]]


In [108]:
embedded_docs[0]

array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0, 3657,
       3987, 3895, 3397,  347, 4561, 2059,  925, 3657,  614])

In [109]:
##model
embedding_vector_features=40
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(LSTM(100))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model.summary())

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 20, 40)            200000    
_________________________________________________________________
lstm_1 (LSTM)                (None, 100)               56400     
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 101       
Total params: 256,501
Trainable params: 256,501
Non-trainable params: 0
_________________________________________________________________
None


In [110]:
len(embedded_docs),label.shape

(44898, (44898,))

In [111]:
x_final=np.array(embedded_docs)
label_final=np.array(label)

In [112]:
x_final.shape,label_final.shape

((44898, 20), (44898,))

In [113]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x_final, label_final, test_size=0.2, random_state=27)

In [114]:
#test model
model.fit(x_train,y_train,validation_data=(x_test,y_test),epochs=5,batch_size=64)

Epoch 1/5
562/562 [==============================] - 13s 19ms/step - loss: 0.3349 - accuracy: 0.8558 - val_loss: 0.1707 - val_accuracy: 0.9344
Epoch 2/5
562/562 [==============================] - 11s 20ms/step - loss: 0.1216 - accuracy: 0.9522 - val_loss: 0.1460 - val_accuracy: 0.9415
Epoch 3/5
562/562 [==============================] - 12s 21ms/step - loss: 0.0847 - accuracy: 0.9688 - val_loss: 0.1506 - val_accuracy: 0.9440
Epoch 4/5
562/562 [==============================] - 13s 23ms/step - loss: 0.0645 - accuracy: 0.9765 - val_loss: 0.1679 - val_accuracy: 0.9430
Epoch 5/5
562/562 [==============================] - 13s 23ms/step - loss: 0.0501 - accuracy: 0.9818 - val_loss: 0.2175 - val_accuracy: 0.9376


In [115]:
#Performance Matrix and Accuracy
y_pred=(model.predict(x_test)>0.5).astype("int32")
print(y_pred)

[[0]
 [0]
 [1]
 ...
 [1]
 [1]
 [1]]


In [116]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_pred)

array([[4461,  200],
       [ 360, 3959]], dtype=int64)

In [117]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test,y_pred)
print(accuracy)

0.9376391982182628


In [76]:
keras_file = 'training_3.h5'

In [77]:
import tensorflow as tf
from tensorflow import keras, lite
tf.keras.models.save_model(model,keras_file)

In [84]:
## converting the model into tensotflow lite
converter =tf.lite.TFLiteConverter.from_keras_model(model)

In [85]:
tflite_model=converter.convert()

INFO:tensorflow:Assets written to: C:\Users\n9hal\AppData\Local\Temp\tmp71twj1tg\assets


INFO:tensorflow:Assets written to: C:\Users\n9hal\AppData\Local\Temp\tmp71twj1tg\assets


In [86]:
open("news_checker_modified.tflite","wb").write(tflite_model)

1037752